[package]
name = "minetest-rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "4.4.11"
configparser = "3.0.3"
mlua = { version = "0.9.2", features = ["luau-jit"] }
spin_sleep = "1.1.1"
traversal = "0.1.2"
