[credits]
minetest_sam = "experiments within minetest C++ GLTF development"
minetest_sam_addition = "a copy of sam was kindly given to the project by core dev Lars"

chair = "the chair was kindly to be allowed for testing from dibesfer in the minetest discord"

[thanks]
thank_you = "to all who helped make model developement on obj and gltf possible"
it_has = "made development more forward quicker and can not be told the gratitude I have for it"
